#!/bin/sh
# TODO: remove sed from the pipeline (currently used to trim leading whitespace)
hs2k | simplemaude "[[ %s ]]" haskell-desugaring-test-compiled.maude | cellstoxml | xpath "//result/text()" | sed 's/^[ \t]*//' | k2hs
